apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bamboo-role
  namespace: bamboo-agent
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - bamboo-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use