---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bamboo-agent-rb
  namespace: bamboo-agent
subjects:
  - kind: ServiceAccount
    name: bamboo-sa
    namespace: bamboo-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin