kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bamboo-agent-home
  namespace: bamboo-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem